### PR TITLE
Rmuolic pbi 285505 remove extra egress section

### PR DESCRIPTION
**Pull request by rmuolic**
Hi @KNyce71, please approve this PR:

- Removed redundant egress section
- Synced topics from adapter framework repo

### CODE REVIEW

**Review by KNyce71 — COMMENTED** [review]
Afternoon @rmuolic....

Just a quick comment....On line 31 in the **prepare-egress-destination** markdown file, the Live Library link has been updated but the text still references the Live Library ("see the PI Web API Guide on Live Library"). 

That should likely be removed or changed to the Documentation Library, right?

**Comment by rmuolic** [comment]
> Afternoon @rmuolic....
> 
> Just a quick comment....On line 31 in the **prepare-egress-destination** markdown file, the Live Library link has been updated but the text still references the Live Library ("see the PI Web API Guide on Live Library").
> 
> That should likely be removed or changed to the Documentation Library, right?

Thanks @KNyce71, myself and Mark missed that. I removed "Live Library" so it just reads "see the PI Web API User Guide".

**Comment by KNyce71** [comment]
Good to go!

**Comment by rmuolic** [comment]
> Good to go!

Thank you @KNyce71 , can you also please approve this PR? Thanks!

**Review by KNyce71 — APPROVED** [review]
Thanks for making the update!

**Pull request merged**
